#!/usr/bin/env node
/**
 * Elm Land cannot load custom Vite plugins, so this script mirrors what
 * elm-tailwind-classes + @tailwindcss/vite do in elm-pages:
 *   1) generate type-safe Elm modules
 *   2) extract used classes via elm-review
 *   3) compile CSS with the Tailwind CLI into src/generated.css
 */
import { execFileSync, spawn } from "node:child_process"
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, "..")
const watch = process.argv.includes("--watch")
const cssPath = path.join(root, "src", "styles.css")
const generateDir = path.join(root, ".elm-tailwind")
const outputCss = path.join(root, "src", "generated.css")
const safelistPath = path.join(generateDir, "safelist.txt")
const wrapperPath = path.join(generateDir, "styles.css")
const extractorConfig = path.join(
  root,
  "node_modules",
  "elm-tailwind-classes",
  "extractor",
)

function bin(name) {
  const local = path.join(root, "node_modules", ".bin", name)
  if (fs.existsSync(local)) return local
  return name
}

async function codegen() {
  const codegenModule = await import(
    path.join(root, "node_modules", "elm-tailwind-classes", "vite-plugin", "codegen.js")
  )
  const result = await codegenModule.generateElmModules(cssPath, generateDir)
  if (!result.success) {
    throw new Error(result.error || "elm-tailwind-classes codegen failed")
  }
  return result.sourceInlines || []
}

function extractClasses() {
  try {
    const output = execFileSync(
      bin("elm-review"),
      ["--extract", "--report=json", "--config", extractorConfig],
      {
        cwd: root,
        encoding: "utf8",
        maxBuffer: 20 * 1024 * 1024,
        stdio: ["ignore", "pipe", "pipe"],
      },
    )
    const result = JSON.parse(output)
    return result.extracts?.TailwindExtractor?.classes || []
  } catch (error) {
    if (error.stdout) {
      try {
        const result = JSON.parse(error.stdout)
        const classes = result.extracts?.TailwindExtractor?.classes || []
        if (classes.length > 0) return classes
      } catch {
        // fall through
      }
    }
    console.warn("[tailwind] class extraction failed; compiling with empty safelist")
    if (error.stderr) console.warn(String(error.stderr).slice(0, 500))
    return []
  }
}

function writeWrapper(sourceInlines, classes) {
  fs.mkdirSync(generateDir, { recursive: true })
  fs.writeFileSync(safelistPath, classes.join(" "))

  let wrapper = `/* Generated by scripts/tailwind.mjs — do not edit */\n`
  wrapper += `@source "./safelist.txt";\n`
  for (const line of sourceInlines) {
    wrapper += `${line}\n`
  }
  wrapper += `\n@import "../src/styles.css";\n`
  fs.writeFileSync(wrapperPath, wrapper)
}

function compileOnce() {
  execFileSync(
    bin("tailwindcss"),
    ["-i", wrapperPath, "-o", outputCss, "--minify"],
    { cwd: root, stdio: "inherit" },
  )
}

function compileWatch() {
  const child = spawn(
    bin("tailwindcss"),
    ["-i", wrapperPath, "-o", outputCss, "--watch"],
    { cwd: root, stdio: "inherit" },
  )
  child.on("exit", (code) => process.exit(code ?? 0))
}

async function main() {
  if (!fs.existsSync(cssPath)) {
    throw new Error(`Missing ${cssPath}`)
  }

  console.log("==> Generating Elm Tailwind modules")
  const sourceInlines = await codegen()

  console.log("==> Extracting used Tailwind classes")
  const classes = extractClasses()
  console.log(`==> ${classes.length} classes in safelist`)

  // Dev watch: include parameterized @source inline() so new Tw.* combos
  // hot-reload without re-extraction. Production: safelist only (small CSS).
  writeWrapper(watch ? sourceInlines : [], classes)

  if (watch) {
    console.log("==> Watching CSS")
    compileWatch()
  } else {
    console.log("==> Compiling CSS")
    compileOnce()
    console.log(`==> Wrote ${path.relative(root, outputCss)}`)
  }
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
